name: Build and publish Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: 'Run dotnet build'
      shell: bash
      run: |
        cd ./src/Backend
        dotnet build --configuration Release
    - name: 'Run dotnet publish'
      shell: bash
      run: |
        cd ./src/Backend
        dotnet publish -o ./output
    - name: 'test1'
      shell: bash
      run: |
        cd ./src/Backend
        ls
    - name: 'test2'
      shell: bash
      run: ls
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: athleticabackend
        publish-profile: ${{ secrets.AZURE_CREDENTIALS_BACKEND }}
