name: Build and publish Mock App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: 'Run dotnet build'
      shell: bash
      env:
        ConnectionStrings__DefaultConnection: secrets.SQL_SERVER_CONNECTION_STRING
      run: |
        pushd ./src/Mock
        dotnet build --configuration Release --output ../../output
        popd
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        package: ./output
        app-name: athleticasignup
        publish-profile: ${{ secrets.AZURE_CREDENTIALS_MOCK }}
